// Auto-generated by tools/embed_mm2_font_8.py
#include "mm2/gfx/mm2_font8x8.h"

#if defined(AMIGA)
#include <ace/managers/memory.h>
#include <mini_std/string.h>
#endif

const uint8_t mm2_font8x8[128][8] = {
#include "Mm2Font8x8_data.inc"
};

#if defined(AMIGA)
static uint8_t *s_font_chip;

void mm2_amiga_font_init(void)
{
    if (s_font_chip) {
        return;
    }
    s_font_chip = (uint8_t *)memAllocChipClear((ULONG)(MM2_FONT8X8_GLYPHS * MM2_FONT8X8_ROWS));
    if (s_font_chip) {
        memcpy(s_font_chip, mm2_font8x8, (size_t)(MM2_FONT8X8_GLYPHS * MM2_FONT8X8_ROWS));
    }
}

void mm2_amiga_font_shutdown(void)
{
    if (s_font_chip) {
        memFree(s_font_chip, (ULONG)(MM2_FONT8X8_GLYPHS * MM2_FONT8X8_ROWS));
        s_font_chip = NULL;
    }
}

const uint8_t *mm2_font8x8_live(void)
{
    return s_font_chip ? s_font_chip : (const uint8_t *)mm2_font8x8;
}
#else
const uint8_t *mm2_font8x8_live(void)
{
    return (const uint8_t *)mm2_font8x8;
}
#endif
