#pragma once

#include "mm2/CppStdCompat.h"
#include "mm2/ui/IPlayHud.h"

namespace mm2::ui {

/** One packed sprite rect inside the Agui RGBA atlas. */
struct AguiAtlasRect {
    int x = 0;
    int y = 0;
    int w = 0;
    int h = 0;
};

/**
 * SDL-side Agui art pack: agui_atlas.rgba + agui_atlas.json under data/ui/agui/.
 * Generated by tools/pack_agui_ui.py from native-resolution indexed PNGs.
 */
class AguiAtlas {
public:
    bool load(const char *data_dir);
    void unload();

    bool ready() const { return rgba_ != nullptr && width_ > 0 && height_ > 0; }

    void blit(gfx::ScreenCompositor &c, const AguiAtlasRect &src, int dst_x, int dst_y) const;

    const AguiAtlasRect *find(const char *name) const;

    static constexpr int kMaxRects = 64;

private:
    uint8_t *rgba_ = nullptr;
    int width_ = 0;
    int height_ = 0;
    AguiAtlasRect rects_[kMaxRects]{};
    char names_[kMaxRects][32]{};
    int rect_count_ = 0;
};

}  // namespace mm2::ui
