#!/usr/bin/env python3
"""Generate concise basic-block annotations for the Capstone listing."""
from __future__ import annotations

import argparse
import re
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "EXTRACTED" / "mm2.capstone.asm"
OUTPUT = ROOT / "EXTRACTED" / "mm2.capstone.block_annotated.asm"
SYMBOLS = ROOT / "EXTRACTED" / "mm2_symbols.yaml"
ROW = re.compile(r"^(?P<addr>[0-9a-fA-F]{6})\s+(?P<bytes>[0-9a-fA-F]+)\s+(?P<mnemonic>\S+)(?:\s+(?P<operands>.*?))?\s*$")
TARGET = re.compile(r"\$([0-9a-fA-F]+)")

BRANCH = {"bra", "bsr", "bhi", "bls", "bcc", "bcs", "bne", "beq", "bvc", "bvs", "bpl", "bmi", "bge", "blt", "bgt", "ble", "jmp", "jsr"}
RETURN = {"rts", "rte", "rtr", "stop"}
WRITE_OPS = {"move", "moveq", "movea", "lea", "clr", "add", "adda", "addq", "sub", "suba", "subq", "and", "or", "eor", "neg", "negx", "not", "asl", "asr", "lsl", "lsr", "rol", "ror", "roxl", "roxr", "bset", "bclr", "bchg", "exg", "swap", "ext"}


def load_symbols(path: Path) -> dict[int, dict]:
    result: dict[int, dict] = {}
    # Avoid requiring PyYAML: the repository symbol file has simple scalar entries.
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    current = None
    for line in lines:
        m = re.match(r"\s*'?(0x[0-9A-Fa-f]+)'?:\s*$", line)
        if m:
            current = int(m.group(1), 16)
            result[current] = {}
            continue
        if current is None:
            continue
        m = re.match(r"\s+name:\s*(\S+)", line)
        if m:
            result[current]["name"] = m.group(1)
        m = re.match(r"\s+note:\s*(.*)", line)
        if m:
            result[current]["note"] = m.group(1).strip()
    return result


def parse(source: Path):
    lines = source.read_text(encoding="utf-8", errors="replace").splitlines()
    rows = []
    by_addr = {}
    for index, line in enumerate(lines):
        m = ROW.match(line)
        if not m:
            continue
        row = {"line": line, "index": index, "addr": int(m.group("addr"), 16), "mnemonic": m.group("mnemonic").lower(), "operands": m.group("operands") or "", "size": len(m.group("bytes")) // 2}
        rows.append(row)
        by_addr[row["addr"]] = row
    return lines, rows


def base(mnemonic: str) -> str:
    return mnemonic.split(".", 1)[0]


def summary(block: list[dict], symbol: dict | None) -> str:
    ops = [base(row["mnemonic"]) for row in block]
    calls = [row["operands"] for row in block if base(row["mnemonic"]) in {"jsr", "bsr"}]
    writes = [row["operands"] for row in block if base(row["mnemonic"]) in WRITE_OPS]
    transfers = [row for row in block if base(row["mnemonic"]) in BRANCH or base(row["mnemonic"]) in RETURN]
    parts = []
    if symbol:
        parts.append(symbol.get("name", "named routine") + ".")
        if symbol.get("note"):
            parts.append(symbol["note"].rstrip(".") + ".")
    if calls:
        parts.append(f"Transfers/calls via {', '.join(calls[:3])}{'…' if len(calls) > 3 else ''}.")
    if writes:
        unique = []
        for item in writes:
            if item not in unique:
                unique.append(item)
        parts.append(f"Updates {', '.join(unique[:4])}{'…' if len(unique) > 4 else ''}.")
    if transfers and not calls:
        parts.append("Ends or branches on control flow; exact path depends on runtime state.")
    if not parts:
        parts.append(f"UNKNOWN BLOCK: {len(block)} instruction(s); operation is preserved but higher-level intent is not established.")
    return " ".join(parts)


def generate(source: Path, output: Path, symbols_path: Path) -> dict[str, int]:
    lines, rows = parse(source)
    symbols = load_symbols(symbols_path)
    # Symbol entries are conservative routine/block boundaries. Do not promote
    # every branch target: the listing includes embedded data disassembled as code.
    row_addresses = {row["addr"] for row in rows}
    leaders = sorted(addr for addr in symbols if addr in row_addresses and 0x1000 <= addr <= 0x40000)
    block_for = {}
    for pos, start in enumerate(leaders):
        end = leaders[pos + 1] if pos + 1 < len(leaders) else None
        block = [row for row in rows if row["addr"] >= start and (end is None or row["addr"] < end)]
        for row in block:
            block_for[row["index"]] = (start, block)
    out = [
        "; mm2.capstone.block_annotated.asm — generated by tools/annotate_capstone_blocks.py",
        "; Concise basic-block summaries; original source rows are preserved verbatim.",
        "; UNKNOWN BLOCK means the bytes are covered but intent is not proven from static evidence.",
        f"; Coverage: source_lines={len(lines)} address_rows={len(rows)} blocks={len(leaders)}",
        "",
    ]
    emitted = set()
    for index, line in enumerate(lines):
        if index in block_for:
            start, block = block_for[index]
            if start not in emitted:
                end = block[-1]["addr"] + block[-1]["size"]
                symbol = symbols.get(start)
                label = symbol.get("name") if symbol else "UNKNOWN BLOCK"
                out.extend([f"; BLOCK-SUMMARY 0x{start:06X}–0x{end:06X}: {label}", f"; BLOCK-NOTE {summary(block, symbol)}"])
                emitted.add(start)
        out.append(line)
    output.write_text("\n".join(out) + "\n", encoding="utf-8")
    return {"source_lines": len(lines), "address_rows": len(rows), "blocks": len(leaders)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--symbols", type=Path, default=SYMBOLS)
    args = parser.parse_args()
    print(generate(args.source, args.output, args.symbols))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
