#!/usr/bin/env python3
"""Generate a conservative, line-by-line annotated Capstone ASM listing."""
from __future__ import annotations

import argparse
import re
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from mm2_symbols import load_symbols, DEFAULT_SYMBOLS

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "EXTRACTED" / "mm2.capstone.asm"
DEFAULT_OUTPUT = ROOT / "EXTRACTED" / "mm2.capstone.line_annotated.asm"
ADDR_RE = re.compile(r"^(?P<addr>[0-9a-fA-F]{6})\s+(?P<bytes>[0-9a-fA-F]+)\s+(?P<mnemonic>\S+)(?:\s+(?P<operands>.*?))?\s*$")

DATA_MNEMONICS = {".byte", ".word", ".long", ".short", ".ascii", ".asciz", ".string"}
BRANCHES = {"bra", "bsr", "bhi", "bls", "bcc", "bcs", "bne", "beq", "bvc", "bvs", "bpl", "bmi", "bge", "blt", "bgt", "ble", "dbra", "dbf", "dbcc", "dbcs", "dbeq", "dbne", "dbhi", "dbls", "dbpl", "dbmi", "dbge", "dblt", "dbgt", "dble", "jmp", "jsr"}


def explain(mnemonic: str, operands: str) -> tuple[str, str]:
    op = mnemonic.lower()
    base = op.split(".", 1)[0]
    if op in DATA_MNEMONICS:
        return "DATA", "Data directive emitted by the disassembler; not proven executable code."
    if op == ".word" or op == ".long":
        return "DATA", "Raw constant data; semantic owner is not established by this listing."
    if op == "rts":
        return "CONTROL", "Return from subroutine; execution resumes at the saved return address."
    if op == "rte":
        return "CONTROL", "Return from exception; restores the saved exception frame."
    if op in {"nop", "reset", "rtr", "stop", "trap", "trapv", "unlk", "link", "exg", "swap", "ext", "extb"}:
        return "KNOWN", f"68000 {op} operation; exact caller/state intent is not established here."
    if base in BRANCHES:
        return "CONTROL", f"{op} transfers control according to its condition/target ({operands}); target reachability is not inferred here."
    if base.startswith("b") and len(base) in {2, 3}:
        return "CONTROL", f"Conditional/control-transfer instruction {op}; exact path depends on condition codes and runtime state."
    if base in {"move", "movea", "moveq", "lea", "pea", "clr", "clrb", "clrw", "clrl", "add", "adda", "addq", "sub", "suba", "subq", "cmp", "cmpa", "tst", "neg", "negx", "not", "and", "or", "eor", "asl", "asr", "lsl", "lsr", "rol", "ror", "roxl", "roxr", "btst", "bset", "bclr", "bchg", "and", "or", "eor", "divs", "divu", "muls", "mulu", "mulu", "abcd", "sbcd", "scc"}:
        return "KNOWN", f"68000 {op} operation on {operands}; updates registers/memory and condition codes as defined by the instruction."
    if op.startswith(".byte"):
        return "DATA", "Raw bytes; semantic interpretation is unresolved."
    return "UNKNOWN", f"Instruction/data semantics not confidently classified beyond Capstone mnemonic {mnemonic} and operands {operands or '<none>'}."


def function_map(symbols_path: Path) -> dict[int, dict]:
    symbols = load_symbols(symbols_path)
    result: dict[int, dict] = {}
    for key, value in symbols.get("functions", {}).items():
        if str(key).lower().startswith("0x"):
            result[int(key, 16)] = value
    return result


def annotate(source: Path, output: Path, symbols_path: Path) -> dict[str, int]:
    source_lines = source.read_text(encoding="utf-8", errors="replace").splitlines()
    funcs = function_map(symbols_path)
    out: list[str] = [
        "; mm2.capstone.line_annotated.asm Ã¢â‚¬â€ generated by tools/annotate_capstone_lines.py",
        "; Every source line is copied verbatim and followed by one compact annotation.",
        f"; Source: {source}",
        "; Semantics are conservative: UNKNOWN means the bytes are represented but intent is not proven.",
        "",
    ]
    address_rows = data_rows = unknown_rows = 0
    for line_no, line in enumerate(source_lines, 1):
        out.append(line)
        match = ADDR_RE.match(line)
        if not match:
            out.append(f"; A {line_no}: STRUCTURAL")
            continue
        address_rows += 1
        kind, text = explain(match.group("mnemonic"), match.group("operands") or "")
        address = int(match.group("addr"), 16)
        symbol = funcs.get(address)
        if symbol:
            text += f" Symbol: {symbol.get('name', '<unnamed>')} ({symbol.get('source', 'unattributed')}). {symbol.get('note', '')}"
        if kind == "DATA":
            data_rows += 1
        elif kind == "UNKNOWN":
            unknown_rows += 1
        short = text.split(" Symbol:", 1)[0].strip()
        if symbol:
            short += "; " + symbol.get("name", "<unnamed>")
        out.append(f"; A {line_no} 0x{address:06X} {kind}: {short}")
    out[4:4] = [
        f"; Coverage: source_lines={len(source_lines)} annotated_source_lines={len(source_lines)} address_rows={address_rows} data_rows={data_rows} unknown_rows={unknown_rows}",
        "",
    ]
    output.write_text("\n".join(out) + "\n", encoding="utf-8")
    return {"source_lines": len(source_lines), "address_rows": address_rows, "data_rows": data_rows, "unknown_rows": unknown_rows}


def verify(source: Path, output: Path) -> dict[str, int]:
    source_lines = source.read_text(encoding="utf-8", errors="replace").splitlines()
    generated = output.read_text(encoding="utf-8", errors="replace").splitlines()
    annotations = [index for index, line in enumerate(generated) if line.startswith("; A ")]
    expected = len(source_lines)
    if len(annotations) != expected:
        raise ValueError(f"annotation mismatch: expected {expected}, found {len(annotations)}")
    copied = [generated[index - 1] for index in annotations]
    if copied != source_lines:
        raise ValueError(f"coverage mismatch: expected {len(source_lines)} source lines, recovered {len(copied)}")
    return {"source_lines": expected, "recovered_source_lines": len(copied), "annotations": len(annotations)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--symbols", type=Path, default=DEFAULT_SYMBOLS)
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    if args.verify:
        print(verify(args.source, args.output))
        return 0
    print(annotate(args.source, args.output, args.symbols))
    print(verify(args.source, args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())




