#!/usr/bin/env python3
"""Apply mm2_symbols.yaml to generate annotated disassembly listings."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from mm2_symbols import DEFAULT_SYMBOLS, IRA_ASM, ROOT, load_symbols  # noqa: E402

CAPSTONE_ASM = ROOT / "EXTRACTED" / "mm2.capstone.asm"
OUT_IRA = ROOT / "EXTRACTED" / "mm2.annotated.asm"
OUT_CAP = ROOT / "EXTRACTED" / "mm2.capstone.annotated.asm"


def _func_by_addr(symbols: dict) -> dict[int, dict]:
    out: dict[int, dict] = {}
    for key, entry in symbols.get("functions", {}).items():
        if key.startswith("0x"):
            out[int(key, 16)] = entry
    return out


def _ira_func_addr_map(src: Path) -> dict[str, int]:
    """Map FUNC_* label → entry address from the following instruction comment."""
    lines = src.read_text(encoding="utf-8", errors="replace").splitlines()
    out: dict[str, int] = {}
    addr_comment = re.compile(r";\s*([0-9a-f]{4,5}):\s", re.I)
    for i, line in enumerate(lines):
        m = re.match(r"^(FUNC_[A-Za-z0-9_]+):", line)
        if not m or i + 1 >= len(lines):
            continue
        am = addr_comment.search(lines[i + 1])
        if am:
            out[m.group(1)] = int(am.group(1), 16)
    return out


def annotate_ira(src: Path, dst: Path, symbols: dict) -> tuple[int, int]:
    funcs = _func_by_addr(symbols)
    func_addrs = _ira_func_addr_map(src)
    label_hits = 0
    addr_hits = 0
    addr_comment = re.compile(r";\s*([0-9a-f]{4,5}):\s", re.I)
    label_line = re.compile(r"^(LAB_[0-9A-Fa-f]+|FUNC_[A-Za-z0-9_]+):")

    raw_lines = src.read_text(encoding="utf-8", errors="replace").splitlines()
    lines_out: list[str] = [
        "; mm2.annotated.asm — generated by tools/apply_symbols.py",
        "; Do not edit by hand; regenerate from EXTRACTED/mm2_symbols.yaml",
        f"; Source: {src.name}",
        "; Note: IRA listing covers code hunk 0 only (~0..0x2C512). Overlay/event",
        ";       code (0x172CA+, 0x2593c+) is in mm2.capstone.annotated.asm.",
        "",
    ]

    for line in raw_lines:
        m_label = label_line.match(line)
        if m_label:
            label = m_label.group(1)
            addr = None
            if label.startswith("LAB_"):
                try:
                    addr = int(label[4:], 16)
                except ValueError:
                    addr = None
            elif label.startswith("FUNC_"):
                addr = func_addrs.get(label)
            if addr is not None and addr in funcs:
                name = funcs[addr]["name"]
                if f"; {name}" not in line:
                    line = f"{line}\t; {name}"
                    label_hits += 1
            lines_out.append(line)
            continue

        m_addr = addr_comment.search(line)
        if m_addr:
            addr = int(m_addr.group(1), 16)
            prev = lines_out[-1] if lines_out else ""
            if addr in funcs and f"; {funcs[addr]['name']}" not in line:
                if not label_line.match(prev):
                    line = f"{line}\t; {funcs[addr]['name']}"
                    addr_hits += 1

        lines_out.append(line)

    dst.write_text("\n".join(lines_out) + "\n", encoding="utf-8")
    return label_hits, addr_hits


def annotate_capstone(src: Path, dst: Path, symbols: dict) -> int:
    funcs = _func_by_addr(symbols)
    addr_line = re.compile(r"^([0-9a-f]{5,6})\s+", re.I)
    last_addr: int | None = None
    commented = 0
    lines_out: list[str] = [
        "; mm2.capstone.annotated.asm — generated by tools/apply_symbols.py",
        "; Do not edit by hand; regenerate from EXTRACTED/mm2_symbols.yaml",
        "",
    ]

    for line in src.read_text(encoding="utf-8", errors="replace").splitlines():
        m = addr_line.match(line)
        if m:
            addr = int(m.group(1), 16)
            if addr in funcs and addr != last_addr:
                name = funcs[addr]["name"]
                recent = "\n".join(lines_out[-10:])
                if name not in recent:
                    src_tag = funcs[addr].get("source", "")
                    lines_out.append(f"; {name} @ 0x{addr:X}  ({src_tag})")
                    commented += 1
            last_addr = addr
        lines_out.append(line)

    dst.write_text("\n".join(lines_out) + "\n", encoding="utf-8")
    return commented


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-s", "--symbols", type=Path, default=DEFAULT_SYMBOLS)
    ap.add_argument("--ira", type=Path, default=IRA_ASM)
    ap.add_argument("--capstone", type=Path, default=CAPSTONE_ASM)
    ap.add_argument("--out-ira", type=Path, default=OUT_IRA)
    ap.add_argument("--out-capstone", type=Path, default=OUT_CAP)
    ap.add_argument("--ira-only", action="store_true")
    ap.add_argument("--capstone-only", action="store_true")
    args = ap.parse_args()

    symbols = load_symbols(args.symbols)
    nf = len(symbols.get("functions", {}))
    if nf == 0:
        print(f"No functions in {args.symbols}; run harvest_symbols.py first", file=sys.stderr)
        return 1

    if not args.capstone_only:
        lh, ah = annotate_ira(args.ira, args.out_ira, symbols)
        print(f"IRA:      {args.out_ira}  ({lh} label comments, {ah} addr comments)")

    if not args.ira_only:
        ch = annotate_capstone(args.capstone, args.out_capstone, symbols)
        print(f"Capstone: {args.out_capstone}  ({ch} function header comments)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
