#!/usr/bin/env python3
"""Emit EXTRACTED/decomp/mm2_amiga_sfx_tables.h from mm2_data_00.bin (doc 58)."""
from __future__ import annotations

import argparse
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATA = ROOT / "EXTRACTED/hunks/mm2_data_00.bin"
DEFAULT_OUT = ROOT / "EXTRACTED/decomp/mm2_amiga_sfx_tables.h"

OFF_WAVE_OFFS = 0xCB4
OFF_WAVE_LENS = 0xCC6
OFF_PERIODS = 0xCD8
OFF_SEQ = 0xD22
OFF_SEQ_END = 0xDAC
OFF_DUR_SFX = 0xDAC
OFF_TITLE = 0x1D79
OFF_TITLE_DUR = 0x1E42
TITLE_INDEX_LIMIT = 0xC5


def u16s(buf: bytes, off: int, n: int) -> list[int]:
    return [struct.unpack_from(">H", buf, off + i * 2)[0] for i in range(n)]


def parse_sequences(data: bytes) -> list[bytes]:
    seqs: list[bytes] = []
    i = OFF_SEQ
    while i < OFF_SEQ_END and len(seqs) < 10:
        start = i
        while i < OFF_SEQ_END and data[i] != 0xFF:
            i += 2
        if i < len(data) and data[i] == 0xFF:
            i += 1
        seqs.append(data[start:i])
    return seqs


def c_bytes(blob: bytes, indent: str = "    ") -> str:
    parts = [f"0x{b:02X}" for b in blob]
    lines: list[str] = []
    for j in range(0, len(parts), 16):
        lines.append(indent + ", ".join(parts[j : j + 16]) + ",")
    return "\n".join(lines)


def c_u16(vals: list[int], indent: str = "    ") -> str:
    parts = [f"0x{v:04X}" for v in vals]
    lines: list[str] = []
    for j in range(0, len(parts), 8):
        lines.append(indent + ", ".join(parts[j : j + 8]) + ",")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", type=Path, default=DEFAULT_DATA)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    data = args.data.read_bytes()
    periods = u16s(data, OFF_PERIODS, 12)
    wave_offs = u16s(data, OFF_WAVE_OFFS, 8)
    wave_lens = u16s(data, OFF_WAVE_LENS, 8)
    dur_sfx = u16s(data, OFF_DUR_SFX, 16)
    dur_title = u16s(data, OFF_TITLE_DUR, 16)
    seqs = parse_sequences(data)
    # Title stream: overlay reads while index < 0xC5 (pairs through byte 0xC5).
    title = data[OFF_TITLE : OFF_TITLE + TITLE_INDEX_LIMIT + 1]

    out: list[str] = []
    out.append("/* Auto-generated by tools/embed_mm2_amiga_sfx_tables.py — do not edit. */")
    out.append("/* Source: EXTRACTED/hunks/mm2_data_00.bin (doc 58 Amiga Paula tables). */")
    out.append("#pragma once")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("#ifdef __cplusplus")
    out.append('extern "C" {')
    out.append("#endif")
    out.append("")
    out.append("#define MM2_AMIGA_SFX_SEQ_COUNT 10")
    out.append(f"#define MM2_AMIGA_TITLE_STREAM_BYTES {len(title)}")
    out.append("#define MM2_AMIGA_TITLE_INDEX_LIMIT 0xC5")
    out.append("")
    out.append("static const uint16_t kMm2AmigaPeriods[12] = {")
    out.append(c_u16(periods))
    out.append("};")
    out.append("")
    out.append("static const uint16_t kMm2AmigaWaveOffs[8] = {")
    out.append(c_u16(wave_offs))
    out.append("};")
    out.append("")
    out.append("static const uint16_t kMm2AmigaWaveLens[8] = {")
    out.append(c_u16(wave_lens))
    out.append("};")
    out.append("")
    out.append("static const uint16_t kMm2AmigaDurSfx[16] = {")
    out.append(c_u16(dur_sfx))
    out.append("};")
    out.append("")
    out.append("static const uint16_t kMm2AmigaDurTitle[16] = {")
    out.append(c_u16(dur_title))
    out.append("};")
    out.append("")
    for i, blob in enumerate(seqs):
        out.append(f"static const uint8_t kMm2AmigaSeq{i}[] = {{")
        out.append(c_bytes(blob))
        out.append("};")
        out.append("")
    out.append("static const uint8_t *const kMm2AmigaSeqs[MM2_AMIGA_SFX_SEQ_COUNT] = {")
    for i in range(10):
        out.append(f"    kMm2AmigaSeq{i},")
    out.append("};")
    out.append("")
    out.append("static const uint8_t kMm2AmigaTitleStream[MM2_AMIGA_TITLE_STREAM_BYTES] = {")
    out.append(c_bytes(title))
    out.append("};")
    out.append("")
    out.append("#ifdef __cplusplus")
    out.append("}")
    out.append("#endif")
    out.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {args.out} ({args.out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
