#!/usr/bin/env python3
"""Embed MM2 8×8 console font for game/src/gfx/Mm2Font8x8.inc.

Prefers decoding EXTRACTED/fonts/mm2/8 (Amiga TextFont hunk). Falls back to
editor/assets/fonts/mm2_8.png + mm2_8.json. Glyphs are encoded LSB column
order (bit 0 = leftmost pixel) to match drawChar in ScreenCompositor.cpp.
"""

from __future__ import annotations

import json
import re
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "game" / "src" / "gfx" / "Mm2Font8x8.inc"
AMIGA_FONT = ROOT / "EXTRACTED" / "fonts" / "mm2" / "8"
PNG_PATH = ROOT / "editor" / "assets" / "fonts" / "mm2_8.png"
JSON_PATH = ROOT / "editor" / "assets" / "fonts" / "mm2_8.json"

HUNK_HEADER = 1011
HUNK_CODE = 1001


def be16(data: bytes, off: int) -> int:
    return struct.unpack_from(">H", data, off)[0]


def be32(data: bytes, off: int) -> int:
    return struct.unpack_from(">I", data, off)[0]


def extract_first_code_hunk(data: bytes) -> bytes:
    if len(data) < 8 or be32(data, 0) != HUNK_HEADER:
        raise ValueError("not an Amiga hunk file")
    for off in range(0, len(data) - 8, 4):
        if be32(data, off) != HUNK_CODE:
            continue
        long_words = be32(data, off + 4)
        start = off + 8
        end = start + long_words * 4
        if end <= len(data):
            return data[start:end]
    raise ValueError("no HUNK_CODE found")


def read_bit_msb(data: bytes, row_start: int, bit_index: int) -> int:
    byte_off = row_start + (bit_index >> 3)
    if byte_off < 0 or byte_off >= len(data):
        return 0
    mask = 0x80 >> (bit_index & 7)
    return 1 if (data[byte_off] & mask) else 0


def decode_from_amiga() -> list[list[int]]:
    from export_mm2_bitmap_font import decode_glyph, find_text_font  # type: ignore

    code = extract_first_code_hunk(AMIGA_FONT.read_bytes())
    tf = find_text_font(code)
    glyphs: list[list[int]] = []
    for cp in range(128):
        _w, h, pix = decode_glyph(code, tf, cp)
        rows: list[int] = []
        for y in range(h):
            byte = 0
            for x in range(8):
                if pix[y * 8 + x]:
                    byte |= 1 << x  # LSB column order
            rows.append(byte)
        glyphs.append(rows)
    return glyphs


def decode_from_png() -> list[list[int]]:
    try:
        from PIL import Image
    except ImportError as exc:
        raise RuntimeError("Pillow required for PNG fallback") from exc

    meta = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    by_cp = {g["codepoint"]: g for g in meta["glyphs"]}
    img = Image.open(PNG_PATH).convert("RGBA")
    glyphs: list[list[int]] = []
    for cp in range(128):
        g = by_cp[cp]
        rows: list[int] = []
        for row in range(8):
            byte = 0
            for col in range(8):
                px = img.getpixel((g["x"] + col, g["y"] + row))
                on = px[3] > 128 and (px[0] + px[1] + px[2]) > 384
                if on:
                    byte |= 1 << col
            rows.append(byte)
        glyphs.append(rows)
    return glyphs


CONTROL_NAMES: dict[int, str] = {
    0x0A: "LF",
    0x0E: "top-bar",
    0x0F: "bot-bar",
    0x10: "TL",
    0x11: "TR",
    0x12: "BL",
    0x13: "BR",
    0x14: "left",
    0x15: "right",
}


def glyph_comment(cp: int) -> str:
    if cp in CONTROL_NAMES:
        return CONTROL_NAMES[cp]
    if cp == 32:
        return "space"
    if cp == 127:
        return "del"
    if cp < 32:
        return f"ctrl-{cp:02x}"
    ch = chr(cp)
    if ch == "\\":
        return "backslash"
    if ch == '"':
        return '\\"'
    return ch


def emit_inc(glyphs: list[list[int]]) -> str:
    lines = [
        "// Auto-generated by tools/embed_mm2_font_8.py (LSB column order; bit 0 = left pixel)",
        "// Indices 0..127 = Amiga font-8 codepoints (control glyphs 0x00..0x1F = UI borders).",
        "static const uint8_t kFont8x8[128][8] = {",
    ]
    for cp, rows in enumerate(glyphs):
        row_txt = ", ".join(f"0x{b:02x}" for b in rows)
        lines.append(f"    {{{row_txt}}},  // {glyph_comment(cp)}")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    sys.path.insert(0, str(ROOT / "tools"))
    if AMIGA_FONT.is_file():
        glyphs = decode_from_amiga()
        source = str(AMIGA_FONT)
    elif PNG_PATH.is_file() and JSON_PATH.is_file():
        glyphs = decode_from_png()
        source = str(PNG_PATH)
    else:
        print("No font source found", file=sys.stderr)
        return 1
    if len(glyphs) != 128:
        print(f"expected 128 glyphs, got {len(glyphs)}", file=sys.stderr)
        return 1
    text = emit_inc(glyphs)
    OUT_PATH.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_PATH} ({len(glyphs)} glyphs from {source})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
