#!/usr/bin/env python3
"""Split annotated Capstone listing into readable subsystem .asm parts."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from mm2_symbols import DEFAULT_SYMBOLS, IRA_ASM, ROOT, load_symbols  # noqa: E402

ASM_DIR = ROOT / "EXTRACTED" / "asm"
REGIONS = ASM_DIR / "regions.yaml"
CAP_ANNOTATED = ROOT / "EXTRACTED" / "mm2.capstone.annotated.asm"
CAP_RAW = ROOT / "EXTRACTED" / "mm2.capstone.asm"

ADDR_LINE = re.compile(r"^([0-9a-f]{5,6})\s+\S", re.I)
LBL_START = re.compile(r";@LBL-START")
LBL_END = re.compile(r";@LBL-END")
LBL_HDR = re.compile(
    r";\s*=+\s*\n;\s*([0-9a-f]{5,6})\s+(\S+.*?)\s*\n",
    re.I,
)


def _load_regions(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    try:
        import yaml  # type: ignore

        data = yaml.safe_load(text)
    except ImportError:
        raise SystemExit("PyYAML required: pip install pyyaml") from None
    return data.get("parts", [])


def _in_ranges(addr: int, ranges: list[list[int]]) -> bool:
    for pair in ranges:
        if len(pair) != 2:
            continue
        lo, hi = int(pair[0]), int(pair[1])
        if lo <= addr <= hi:
            return True
    return False


def _parse_listing(path: Path) -> tuple[list[str], dict[int, int]]:
    """Return all lines and map addr -> first line index (instruction lines only)."""
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    addr_index: dict[int, int] = {}
    for i, line in enumerate(lines):
        m = ADDR_LINE.match(line)
        if m:
            addr = int(m.group(1), 16)
            addr_index.setdefault(addr, i)
    return lines, addr_index


def _collect_lbl_blocks(lines: list[str]) -> dict[int, list[str]]:
    """Map instruction address -> preceding @LBL comment block (if any)."""
    blocks: dict[int, list[str]] = {}
    pending: list[str] = []
    in_block = False
    for i, line in enumerate(lines):
        if LBL_START.search(line):
            in_block = True
            pending = [line]
            continue
        if in_block:
            pending.append(line)
            if LBL_END.search(line):
                in_block = False
                # Next instruction line gets this block
                for j in range(i + 1, min(i + 5, len(lines))):
                    m = ADDR_LINE.match(lines[j])
                    if m:
                        blocks[int(m.group(1), 16)] = pending
                        break
                pending = []
            continue
        if not ADDR_LINE.match(line) and not in_block:
            pending = []
    return blocks


def _func_index(symbols: dict, lo: int, hi: int) -> list[tuple[int, str, str]]:
    rows: list[tuple[int, str, str]] = []
    for key, entry in symbols.get("functions", {}).items():
        if not key.startswith("0x"):
            continue
        addr = int(key, 16)
        if lo <= addr <= hi:
            note = entry.get("note", "")
            rows.append((addr, entry["name"], note))
    rows.sort()
    return rows


def _part_bounds(ranges: list[list[int]]) -> tuple[int, int]:
    lo = min(int(p[0]) for p in ranges)
    hi = max(int(p[1]) for p in ranges)
    return lo, hi


def _is_good_symbol_name(name: str) -> bool:
    if len(name) < 3:
        return False
    if name.isdigit() or name == "unknown":
        return False
    if re.match(r"^OP_\d", name, re.I):
        return False
    if name in ("var", "bchg", "addq", "Read"):
        return False
    return bool(re.match(r"^[a-z][a-z0-9_]*$", name))


def _banner(name: str, addr: int, note: str) -> list[str]:
    out = [
        "; " + "=" * 72,
        f"; {name}  @ 0x{addr:X}",
    ]
    if note:
        out.append(f"; {note}")
    out.append("; " + "=" * 72)
    return out


def build_part(
    part: dict,
    all_lines: list[str],
    addr_index: dict[int, int],
    lbl_blocks: dict[int, list[str]],
    symbols: dict,
    seen_banners: set[int],
) -> str:
    ranges = part["ranges"]
    lo, hi = _part_bounds(ranges)

    # Collect addresses belonging to this part
    addrs = sorted(a for a in addr_index if _in_ranges(a, ranges))

    out: list[str] = [
        f"; {part['file']} — {part['title']}",
        f"; Generated by tools/extract_asm_parts.py — DO NOT EDIT",
        f"; Doc: {part.get('doc', '(none)')}",
        ";",
    ]
    for intro_line in part.get("intro", "").strip().splitlines():
        out.append(f"; {intro_line}")
    out.append(";")
    out.append("; --- Entry points in this file (from mm2_symbols.yaml) ---")
    for addr, name, note in _func_index(symbols, lo, hi):
        if not _is_good_symbol_name(name):
            continue
        suffix = f" — {note}" if note else ""
        out.append(f";   0x{addr:05X}  {name}{suffix}")
    out.append(";")
    out.append("")

    last_addr = -1
    for addr in addrs:
        i = addr_index[addr]
        # Attach @LBL block once per address
        if addr in lbl_blocks and addr != last_addr:
            for bl in lbl_blocks[addr]:
                out.append(bl)

        entry = symbols.get("functions", {}).get(f"0x{addr:X}")
        if (
            entry
            and _is_good_symbol_name(entry["name"])
            and addr not in seen_banners
        ):
            out.extend(_banner(entry["name"], addr, entry.get("note", "")))
            seen_banners.add(addr)

        out.append(all_lines[i])
        last_addr = addr

    return "\n".join(out) + "\n"


def write_readme(parts: list[dict], out_dir: Path) -> None:
    lines = [
        "# MM2 executable — subsystem disassembly parts",
        "",
        "Readable slices of `mm2.capstone.annotated.asm`, grouped by game system.",
        "Regenerate after doc/symbol updates:",
        "",
        "```powershell",
        "python tools\\harvest_symbols.py --merge",
        "python tools\\apply_symbols.py",
        "python tools\\extract_asm_parts.py",
        "```",
        "",
        "## Files",
        "",
        "| File | Subsystem | Doc |",
        "|------|-----------|-----|",
    ]
    for p in parts:
        lines.append(f"| [{p['file']}]({p['file']}) | {p['title']} | `{p.get('doc', '')}` |")
    lines.extend(
        [
            "",
            "## Address rules",
            "",
            "- All addresses are **code-hunk load addresses** (Capstone base 0).",
            "- `A4 = $7FFE` — game state is `offset(A4)`; see `EXTRACTED/decomp/mm2_gamestate.h`.",
            "- **IRA** listing (`mm2.asm`) covers hunk 0 only (~0..0x2C512); overlay and",
            "  most event/combat/town code appear only in these Capstone-based parts.",
            "- Lines may appear in **multiple** parts when address ranges overlap (combat + spells).",
            "",
            "## Related",
            "",
            "- Symbol table: `EXTRACTED/mm2_symbols.yaml`",
            "- Full listing: `EXTRACTED/mm2.capstone.annotated.asm`",
            "- Focused docs: `EXTRACTED/docs/`",
        ]
    )
    (out_dir / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-r", "--regions", type=Path, default=REGIONS)
    ap.add_argument(
        "-i",
        "--input",
        type=Path,
        default=CAP_ANNOTATED,
        help="Annotated capstone asm (falls back to raw capstone)",
    )
    ap.add_argument("-o", "--output-dir", type=Path, default=ASM_DIR)
    ap.add_argument("-s", "--symbols", type=Path, default=DEFAULT_SYMBOLS)
    args = ap.parse_args()

    src = args.input if args.input.is_file() else CAP_RAW
    if not src.is_file():
        print(f"Missing input: {src}", file=sys.stderr)
        return 1
    if not args.regions.is_file():
        print(f"Missing regions: {args.regions}", file=sys.stderr)
        return 1

    parts = _load_regions(args.regions)
    symbols = load_symbols(args.symbols)
    all_lines, addr_index = _parse_listing(src)
    lbl_blocks = _collect_lbl_blocks(all_lines)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    seen_global: set[int] = set()

    for part in parts:
        body = build_part(part, all_lines, addr_index, lbl_blocks, symbols, seen_global)
        out_path = args.output_dir / part["file"]
        out_path.write_text(body, encoding="utf-8")
        insn_count = body.count("\n") - body.count("\n;")
        print(f"  {part['file']:30s}  {len(body.splitlines()):6d} lines")

    write_readme(parts, args.output_dir)
    print(f"\nWrote {len(parts)} parts + README.md -> {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
